In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sudalairajkumar/covid19-in-india")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'covid19-in-india' dataset.
Path to dataset files: /kaggle/input/covid19-in-india

In [ ]:
import os

print(os.listdir(path))

['StatewiseTestingDetails.csv', 'covid_vaccine_statewise.csv', 'covid_19_india.csv']

In [ ]:
import pandas as pd

df = pd.read_csv(path + "/covid_19_india.csv")
df.head(10)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
5,6,2020-02-04,6:00 PM,Kerala,3,0,0,0,3
6,7,2020-02-05,6:00 PM,Kerala,3,0,0,0,3
7,8,2020-02-06,6:00 PM,Kerala,3,0,0,0,3
8,9,2020-02-07,6:00 PM,Kerala,3,0,0,0,3
9,10,2020-02-08,6:00 PM,Kerala,3,0,0,0,3

In [ ]:
df["State/UnionTerritory"]

0               Kerala
1               Kerala
2               Kerala
3               Kerala
4               Kerala
             ...
18105        Telangana
18106          Tripura
18107      Uttarakhand
18108    Uttar Pradesh
18109      West Bengal
Name: State/UnionTerritory, Length: 18110, dtype: object

In [ ]:
df.isnull().sum()

Sno                         0
Date                        0
Time                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Confirmed                   0
dtype: int64

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18105    False
18106    False
18107    False
18108    False
18109    False
Length: 18110, dtype: bool

In [ ]:
df.drop_duplicates()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sno                       18110 non-null  int64
 1   Date                      18110 non-null  object
 2   Time                      18110 non-null  object
 3   State/UnionTerritory      18110 non-null  object
 4   ConfirmedIndianNational   18110 non-null  object
 5   ConfirmedForeignNational  18110 non-null  object
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Confirmed                 18110 non-null  int64
dtypes: int64(4), object(5)
memory usage: 1.2+ MB

In [ ]:

df.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3

In [ ]:
df[df["State/UnionTerritory"] == "Kerala"]

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
17946,17947,2021-08-07,8:00 AM,Kerala,-,-,3317314,17515,3513551
17982,17983,2021-08-08,8:00 AM,Kerala,-,-,3337579,17654,3533918
18018,18019,2021-08-09,8:00 AM,Kerala,-,-,3357687,17747,3552525
18054,18055,2021-08-10,8:00 AM,Kerala,-,-,3377691,17852,3565574
18090,18091,2021-08-11,8:00 AM,Kerala,-,-,3396184,18004,3586693

In [ ]:
df.isnull().sum()

Sno                         0
Date                        0
Time                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Confirmed                   0
dtype: int64

In [ ]:
df.isnull().sum()

Sno                         0
Date                        0
Time                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Confirmed                   0
dtype: int64

In [ ]:

#short krte hai ab
df.sort_values("Confirmed")

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
10387,10388,2021-01-09,8:00 AM,Lakshadweep,-,-,0,0,0
10603,10604,2021-01-15,8:00 AM,Lakshadweep,-,-,0,0,0
9703,9704,2020-12-21,8:00 AM,Lakshadweep,-,-,0,0,0
9883,9884,2020-12-26,8:00 AM,Lakshadweep,-,-,0,0,0
9559,9560,2020-12-17,8:00 AM,Lakshadweep,-,-,0,0,0
...,...,...,...,...,...,...,...,...,...
17950,17951,2021-08-07,8:00 AM,Maharashtra,-,-,6130137,133717,6341759
17986,17987,2021-08-08,8:00 AM,Maharashtra,-,-,6139493,133845,6347820
18022,18023,2021-08-09,8:00 AM,Maharashtra,-,-,6144388,133996,6353328
18058,18059,2021-08-10,8:00 AM,Maharashtra,-,-,6151956,134064,6357833
18094,18095,2021-08-11,8:00 AM,Maharashtra,-,-,6159676,134201,6363442

In [ ]:
kerala = df[df["State/UnionTerritory"] == "Kerala"]
kerala["Confirmed"].sum()

np.int64(458906023)

In [ ]:

#top case confirmed
df.sort_values("Confirmed", ascending=False).head(1)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
18094,18095,2021-08-11,8:00 AM,Maharashtra,-,-,6159676,134201,6363442

In [ ]:
#sabse jyda case kb huye
df.sort_values("Confirmed", ascending=False)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
18094,18095,2021-08-11,8:00 AM,Maharashtra,-,-,6159676,134201,6363442
18058,18059,2021-08-10,8:00 AM,Maharashtra,-,-,6151956,134064,6357833
18022,18023,2021-08-09,8:00 AM,Maharashtra,-,-,6144388,133996,6353328
17986,17987,2021-08-08,8:00 AM,Maharashtra,-,-,6139493,133845,6347820
17950,17951,2021-08-07,8:00 AM,Maharashtra,-,-,6130137,133717,6341759
...,...,...,...,...,...,...,...,...,...
10099,10100,2021-01-01,8:00 AM,Lakshadweep,-,-,0,0,0
9883,9884,2020-12-26,8:00 AM,Lakshadweep,-,-,0,0,0
9487,9488,2020-12-15,8:00 AM,Lakshadweep,-,-,0,0,0
9451,9452,2020-12-14,8:00 AM,Lakshadweep,-,-,0,0,0
9415,9416,2020-12-13,8:00 AM,Lakshadweep,-,-,0,0,0

In [ ]:
df.groupby("State/UnionTerritory")["Confirmed"].max()

State/UnionTerritory
Andaman and Nicobar Islands                    7548
Andhra Pradesh                              1985182
Arunachal Pradesh                             50605
Assam                                        576149
Bihar                                        725279
Bihar****                                    715730
Cases being reassigned to states               9265
Chandigarh                                    61992
Chhattisgarh                                1003356
Dadra and Nagar Haveli                        10377
Dadra and Nagar Haveli and Daman and Diu      10654
Daman & Diu                                       2
Delhi                                       1436852
Goa                                          172085
Gujarat                                      825085
Haryana                                      770114
Himachal Pradesh                             208616
Himanchal Pradesh                            204516
Jammu and Kashmir                            322771
Jharkhand                                    347440
Karanataka                                  2885238
Karnataka                                   2921049
Kerala                                      3586693
Ladakh                                        20411
Lakshadweep                                   10263
Madhya Pradesh                               791980
Madhya Pradesh***                            791656
Maharashtra                                 6363442
Maharashtra***                              6229596
Manipur                                      105424
Meghalaya                                     69769
Mizoram                                       46320
Nagaland                                      28811
Odisha                                       988997
Puducherry                                   121766
Punjab                                       599573
Rajasthan                                    953851
Sikkim                                        28018
Tamil Nadu                                  2579130
Telangana                                    650353
Telengana                                    443360
Tripura                                       80660
Unassigned                                       77
Uttar Pradesh                               1708812
Uttarakhand                                  342462
West Bengal                                 1534999
Name: Confirmed, dtype: int64

In [ ]:
df.groupby("State/UnionTerritory")["Confirmed"].sum()      #konse state me kitne case huye hai

State/UnionTerritory
Andaman and Nicobar Islands                    1938498
Andhra Pradesh                               392432753
Arunachal Pradesh                              7176907
Assam                                         99837011
Bihar                                        132231166
Bihar****                                      1430909
Cases being reassigned to states                345565
Chandigarh                                    10858627
Chhattisgarh                                 163776262
Dadra and Nagar Haveli                           20722
Dadra and Nagar Haveli and Daman and Diu       1938632
Daman & Diu                                          2
Delhi                                        287227765
Goa                                           28240159
Gujarat                                      143420082
Haryana                                      134347285
Himachal Pradesh                              30033289
Himanchal Pradesh                               204516
Jammu and Kashmir                             58117726
Jharkhand                                     62111994
Karanataka                                     2885238
Karnataka                                    485970693
Kerala                                       458906023
Ladakh                                         4054293
Lakshadweep                                     915784
Madhya Pradesh                               135625265
Madhya Pradesh***                               791656
Maharashtra                                 1121491467
Maharashtra***                                 6229596
Manipur                                       12617943
Meghalaya                                      7355969
Mizoram                                        2984732
Nagaland                                       5041742
Odisha                                       160130533
Puducherry                                    20065891
Punjab                                        99949702
Rajasthan                                    162369656
Sikkim                                         3186799
Tamil Nadu                                   431928644
Telangana                                     60571979
Telengana                                     69990668
Tripura                                       14050250
Unassigned                                         161
Uttar Pradesh                                312625843
Uttarakhand                                   53140414
West Bengal                                  263107876
Name: Confirmed, dtype: int64

In [ ]:
df["Deaths"].sum()

np.int64(73389005)

In [ ]:
df.loc[230:234, ["State/UnionTerritory", "Deaths", "Cured"]]

    State/UnionTerritory  Deaths  Cured
230                Delhi       1      5
231              Gujarat       0      0
232              Haryana       0      0
233            Karnataka       1      1
234               Kerala       0      3

In [ ]:
df.loc[45, ["State/UnionTerritory", "Deaths", "Cured"]]

State/UnionTerritory    Delhi
Deaths                      0
Cured                       0
Name: 45, dtype: object

In [ ]:

df.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3

In [ ]:

df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df.loc[0, "Deaths"]

np.int64(0)

In [ ]:

df.loc[5, "ConfirmedForeignNational"]

'0'

In [ ]:
df.loc[5, "ConfirmedForeignNational"]

'0'

In [ ]:
df.sample(10)    #rendom de raha ye

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
1822,1823,2020-05-11,8:00 AM,Maharashtra,-,-,4199,832,22171
3526,3527,2020-06-28,8:00 AM,Tripura,-,-,1071,1,1334
5511,5512,2020-08-24,8:00 AM,Andaman and Nicobar Islands,-,-,1963,33,2860
14695,14696,2021-05-09,8:00 AM,Chandigarh,-,-,40249,558,49312
5330,5331,2020-08-18,8:00 AM,Tamil Nadu,-,-,283937,5886,343945
13844,13845,2021-04-15,8:00 AM,Ladakh,-,-,10095,132,11278
11336,11337,2021-02-04,8:00 AM,Tamil Nadu,-,-,823001,12371,839866
2943,2944,2020-06-12,8:00 AM,Odisha,-,-,2354,9,3386
1297,1298,2020-04-25,5:00 PM,Himachal Pradesh,-,-,18,1,40
15936,15937,2021-06-12,8:00 AM,Meghalaya,-,-,35393,714,41100

In [ ]:
state_data = df.groupby("")

KeyError: ''

In [ ]:

df.shape

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sno                       18110 non-null  int64
 1   Date                      18110 non-null  datetime64[ns]
 2   Time                      18110 non-null  object
 3   State/UnionTerritory      18110 non-null  object
 4   ConfirmedIndianNational   18110 non-null  object
 5   ConfirmedForeignNational  18110 non-null  object
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Confirmed                 18110 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 1.2+ MB

In [ ]:

df.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3